config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end


devise_for :users, controllers: {
  registrations: 'users/registrations'
}

resources :users, only: [:show]




  get 'home/about'
  get 'home/upgrade'
  get 'posts/myposts'
  post 'like', to: 'posts#like'
  post 'stripe/webhooks', to: 'stripe/webhooks#create'
  get 'pricing', to: 'stripe/checkout#pricing'
  post 'stripe/checkout', to: 'stripe/checkout#checkout'
  get 'stripe/checkout/success', to: 'stripe/checkout#success'
  get 'stripe/checkout/cancel', to: 'stripe/checkout#cancel'
  post 'stripe/billing_portal', to: 'stripe/billing_portal#create'

  # stripe listen --forward-to localhost:4242/stripe/webhooks


  resources :posts do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/controllers/stripe/billing_portal_controller.rb
class Stripe::BillingPortalController < ApplicationController
   def create

     session = Stripe::BillingPortal::Session.create({
                                                    customer: current_user.stripe_customer_id,
                                                    return_url: pricing_url
                                                  })
     redirect_to session.url, allow_other_host: true
   end
end

app/controllers/stripe/checkout_controller.rb
class Stripe::CheckoutController < ApplicationController

def pricing
lookup_keys = %w[editor admin]
@prices = Stripe::Price.list(lookup_keys: lookup_keys, active: true, expand: ['data.product']).data.sort_by(&:unit_amount)
end


def checkout
    session = Stripe::Checkout::Session.create({
      customer: current_user.stripe_customer_id,
      mode: 'subscription',
      line_items: [{
        quantity: 1,
        price: params[:price_id]
      }],
      success_url: stripe_checkout_success_url,
      cancel_url: stripe_checkout_cancel_url
    })

  redirect_to session.url, allow_other_host: true

end

def success
flash[:notice] = "success"
redirect_to pricing_path
end

def cancel
  flash[:notice] = "failure"
  redirect_to pricing_path
end


end

app/controllers/stripe/webhooks_controller.rb
class Stripe::WebhooksController < ApplicationController
   skip_before_action :verify_authenticity_token



  def create

    webhook_secret = 'whsec_bb8e131d1c6fd228332c3ea6111c531bbd3c0e87d2c7ba5ab65d288c59595c89'
    payload = request.body.read
    if !webhook_secret.empty?
      # Retrieve the event by verifying the signature using the raw body and secret if webhook signing is configured.
      sig_header = request.env['HTTP_STRIPE_SIGNATURE']
      event = nil

      begin
        event = Stripe::Webhook.construct_event(
          payload, sig_header, webhook_secret
        )
      rescue JSON::ParserError => e
        # Invalid payload
        status 400
        return
      rescue Stripe::SignatureVerificationError => e
        # Invalid signature
        puts '⚠️  Webhook signature verification failed.'
        status 400
        return
      end
    else
      data = JSON.parse(payload, symbolize_names: true)
      event = Stripe::Event.construct_from(data)
    end
    # Get the type of webhook event sent - used to check the status of PaymentIntents.
    event_type = event['type']
    data = event['data']
    data_object = data['object']

case event.type
when 'customer.created'
  customer = event.data.object
  user = User.find_by(email: customer.email)
  user.update(stripe_customer_id: customer.id)

when event.type == 'customer.subscription.deleted', 'customer.subscription.updated','customer.subscription.created'
   subscription = event.data.object
   user = User.find_by(stripe_customer_id: subscription.customer)
    user.update(
    plan: subscription.items.data[0].price.recurring.interval,
    subscription_status: subscription.status,
    subscription_ends_at: Time.at(subscription.current_period_end).to_datetime
 )


 case subscription.items.data[0].price.lookup_key
     when 'editor'
       user.update(role: 'editor')
    when 'admin'
       user.update(role: 'admin')

    end





end

    render json: {message: 'success'}

   end
end

app/views/stripe/checkout/pricing.html.erb
<%= button_to 'Billing portal', stripe_billing_portal_path,data: { turbo: "false"} %>
<div class="d-flex justify-content-around">

<div class="card">
    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script> 


    <lottie-player src="https://lottie.host/69718adb-4517-4de8-88ef-d1ddb7b39445/9SmftKAcfk.json" background="transparent" speed="1" style="width: 350px; height: 350px;" loop autoplay></lottie-player>
<b><center>
    <p>Price - 5 rupee</p>
    </center></b>
<div class="container"><p><b>Admin subscription allows you to:-</b>

    <div class="d-flex flex-column">
  <div class="p-2">*Edit any post</div>
  <div class="p-2">*Destroy any post</div>
  <div class="p-2">*Create Unlimited posts </div>
  <div class="p-2">*Read/Delete any comments</div>
</p>
</div>
</div>


</div>

<div class="card">
<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script> 


    <lottie-player src="https://lottie.host/8356376b-0575-4142-897a-68c952218520/4NlcNSztCc.json" background="transparent" speed="1" style="width: 350px; height: 350px;" loop autoplay></lottie-player>
<b><center>
    <p>Price - 10 rupee</p>
    </center></b>
<div class="container"><p><b>Admin subscription allows you to:-</b>

    <div class="d-flex flex-column">
  <div class="p-2">*Edit any post</div>
  <div class="p-2">*Destroy its own</div>
  <div class="p-2">*Create Unlimited posts </div>
</p>
</div>
  
</div>
</div>


</div>
<div class="d-flex justify-content-around">
<% @prices.each do |price| %>
<div>



    

<br><%= button_to 'Subscribe', stripe_checkout_path(price_id: price.id), data: {turbo: 'false'} ,class: "btn btn-primary"%>

</div>
<% end %>
</div>